events {}

http {
  upstream safargo_backend {
    server backend:8080;
  }

  upstream safargo_frontend {
    server frontend:80;
  }

  server {
    listen 80;
    server_name safargo.local;

    location /api/ {
      proxy_pass http://safargo_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api-docs {
      proxy_pass http://safargo_backend;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://safargo_frontend;
      proxy_set_header Host $host;
    }
  }
}
